name: CI
on:
  push:
    branches:
      - ci-test
defaults:
  run:
    working-directory: service
jobs:
  deploy-prd:
    name: deploy prd
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: create-json-sheets-service-account
        id: 'create-json-sheets-service-account'
        uses: jsdaniell/create-json@v1.2.3
        env:
          SHEETS_SERVICE_ACCOUNT_JSON_STRING: ${{ secrets.SHEETS_SERVICE_ACCOUNT_JSON_STRING }}
        with:
          name: "sheetsServiceAcc.json"
          json: $SHEETS_SERVICE_ACCOUNT_JSON_STRING
          dir: "service/"
      - name: create-json
        id: 'create-json-sheets-auth-keys'
        uses: jsdaniell/create-json@v1.2.3
        env:
          AUTH_KEYS_JSON_STRING: ${{ secrets.AUTH_KEYS_JSON_STRING }}
        with:
          name: "authKeys.json"
          json: $AUTH_KEYS_JSON_STRING
          dir: "service/"
      - name: 'debug'
        run: |
          ls -la
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: build
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
        run: |
          gcloud auth configure-docker $DOCKER_REGISTRY
          docker build -t refugio-rs-server:latest .
          docker tag refugio-rs-server:latest "$DOCKER_REGISTRY/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD)"
          docker push $DOCKER_REGISTRY/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD)
      - name: deploy-service
        run: |
          gcloud --project=${{ vars.GCP_PROJECT }} \
            run deploy refugio-rs-prd \
            --image ${{ vars.DOCKER_REGISTRY }}/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD) \
            --platform managed \
            --region southamerica-east1 \
            --memory 256Mi \
            --command /server \
            --args web \
            --set-env-vars=SHEETS_SERVICE_ACCOUNT_JSON="sheetsServiceAcc.json",\
                           ALGOLIA_CLIENT=${{ secrets.ALGOLIA_CLIENT }},\
                           ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }},\
                           ALGOLIA_INDEX="PessoasAbrigoINDEX",\
                           FIRESTORE_PROJECT_ID=${{ vars.GCP_PROJECT }},\
                           AUTH_KEYS_FILE="authKeys.json"
      - name : smoke test
        run: |
          status_code=$(curl -L -o /dev/null -s -w "%{http_code}" -H "Authorization: ${{ secrets.FRONTEND_API_KEY }}" "https://refugio-rs-prd-d5zml3w7fa-rj.a.run.app/pessoa?nome=Joao")
          if [[ $status_code -gt 399 ]]; then
            echo "Status code $status_code"
            exit 1
          fi