name: CI
on:
  push:
    branches:
      - ci-test
    path:
      - service/**
defaults:
  run:
    working-directory: service
jobs:
  deploy-prd:
    name: deploy prd
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: create-json-sheets-service-account
        id: 'create-json-sheets-service-account'
        uses: jsdaniell/create-json@v1.2.3
        env:
          SHEETS_SERVICE_ACCOUNT_JSON_STRING: ${{ secrets.SHEETS_SERVICE_ACCOUNT_JSON_STRING }}
        with:
          name: "sheetsServiceAcc.json"
          json: $SHEETS_SERVICE_ACCOUNT_JSON_STRING
          dir: "service/"
      - name: create-json
        id: 'create-json-sheets-auth-keys'
        uses: jsdaniell/create-json@v1.2.3
        env:
          AUTH_KEYS_JSON_STRING: ${{ secrets.AUTH_KEYS_JSON_STRING }}
        with:
          name: "authKeys.json"
          json: $AUTH_KEYS_JSON_STRING
          dir: "service/"
      - name: 'debug'
        run: |
          cat authKeys.json
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: build
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
        run: |
          gcloud auth configure-docker $DOCKER_REGISTRY
          docker build -t refugio-rs-server:latest .
          docker tag refugio-rs-server:latest "$DOCKER_REGISTRY/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD)"
          docker push $DOCKER_REGISTRY/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD)
      - name: deploy-service
        env :
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          ALGOLIA_CLIENT: ${{ secrets.ALGOLIA_CLIENT }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          gcloud --project=${{ vars.GCP_PROJECT }} \
            run deploy refugio-rs-stg \
            --image ${{ vars.DOCKER_REGISTRY }}/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD) \
            --platform managed \
            --region southamerica-east1 \
            --memory 256Mi \
            --command /server \
            --args web \
            --set-env-vars=SHEETS_SERVICE_ACCOUNT_JSON="sheetsServiceAcc.json",ALGOLIA_CLIENT=$ALGOLIA_CLIENT,ALGOLIA_API_KEY=$ALGOLIA_API_KEY,ALGOLIA_INDEX="PessoasAbrigoINDEX",FIRESTORE_PROJECT_ID=${{ vars.GCP_PROJECT }},AUTH_KEYS_FILE="authKeys.json"
      - name : smoke test and revert
        run: |
          status_code=$(curl -L -o /dev/null -s -w "%{http_code}" -H "Authorization: ${{ secrets.FRONTEND_API_KEY }}" "https://refugio-rs-stg-d5zml3w7fa-rj.a.run.app/pessoa?nome=Joao")
          if [[ $status_code -lt 400 ]]; then
            echo "Status code $status_code. Reverting deployment."
            REVISIONS=$(gcloud run revisions list --service=refugio-rs-stg --region=southamerica-east1 --format=json)
            PREVIOUS_REVISION=$(jq -r '.[1].metadata.name' <<< ${REVISIONS})
            NEW_REVISION=$(jq -r '.[0].metadata.name' <<< ${REVISIONS})
            gcloud run services update-traffic refugio-rs-stg --region=southamerica-east1 --to-revisions=$PREVIOUS_REVISION=100,$NEW_REVISION=0
            exit 1
          fi
      # - name: Discord notification
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #   uses: Ilshidur/action-discord@master
      #   with:
      #     args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
