name: CI
on:
  push:
    branches:
      - ci-test
    # paths:
    #   - service/**
defaults:
  run:
    working-directory: service
jobs:
  deploy-prd:
    name: deploy prd
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: create-json-sheets-service-account
        id: 'create-json-sheets-service-account'
        uses: jsdaniell/create-json@v1.2.3
        env:
          SHEETS_SERVICE_ACCOUNT_JSON_STRING: ${{ secrets.SHEETS_SERVICE_ACCOUNT_JSON_STRING }}
        with:
          name: "sheetsServiceAcc.json"
          json: ${{ secrets.SHEETS_SERVICE_ACCOUNT_JSON_STRING }}
          dir: "service/"
      - name: create-json
        id: 'create-json-sheets-auth-keys'
        uses: jsdaniell/create-json@v1.2.3
        env:
          AUTH_KEYS_JSON_STRING: ${{ secrets.AUTH_KEYS_JSON_STRING }}
        with:
          name: "authKeys.json"
          json: ${{ secrets.AUTH_KEYS_JSON_STRING }}
          dir: "service/"
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: build
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
        run: |
          gcloud auth configure-docker $DOCKER_REGISTRY
          docker build -t refugio-rs-server:latest .
          docker tag refugio-rs-server:latest "$DOCKER_REGISTRY/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD)"
          docker push $DOCKER_REGISTRY/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD)
      - name: deploy-service
        id: deploy-service
        env :
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          ALGOLIA_CLIENT: ${{ secrets.ALGOLIA_CLIENT }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          RESULT=$(gcloud --project=${{ vars.GCP_PROJECT }} \
            run deploy refugio-rs-stg \
            --format=json \
            --image ${{ vars.DOCKER_REGISTRY }}/${{ vars.GCP_PROJECT }}/refugio-rs-server/refugio-rs-server:$(git rev-parse --short HEAD) \
            --platform managed \
            --region southamerica-east1 \
            --memory 256Mi \
            --command /server \
            --args web \
            --set-env-vars=SHEETS_SERVICE_ACCOUNT_JSON="sheetsServiceAcc.json",ALGOLIA_CLIENT=$ALGOLIA_CLIENT,ALGOLIA_API_KEY=$ALGOLIA_API_KEY,ALGOLIA_INDEX="PessoasAbrigoINDEX",FIRESTORE_PROJECT_ID=${{ vars.GCP_PROJECT }},AUTH_KEYS_FILE="authKeys.json");
          LATEST_CREATED=$(jq -r '.status.latestCreatedRevisionName' <<< ${RESULT});
          LATEST_READY=$(jq -r '.status.latestReadyRevisionName' <<< ${RESULT});
          echo $LATEST_CREATED;
          echo $LATEST_READY;
          if [[ $LATEST_CREATED == $LATEST_READY ]]; then
            echo "success=success" >> $GITHUB_OUTPUT
          else
            echo "success=failure" >> $GITHUB_OUTPUT
          fi
      - name: debug
        run: |
          echo ${{ steps.deploy-service.success }}
      - name: Discord Webhook Action
        if: ${{ steps.deploy-service.success }} == 'success'
        uses: tsickert/discord-webhook@v6.0.0
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "Deployment for ${{ github.event.repository.full_name }} successful."
          embed-color: 65280
          embed-url: "https://github.com/buscaresgatados/pesquisa-listas/actions"
      - name: Discord Webhook Action
        if: ${{ steps.deploy-service.success }} == 'failure'
        uses: tsickert/discord-webhook@v6.0.0
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "Deployment for ${{ github.event.repository.full_name }} failure."
          embed-color: 16711680
          embed-url: https://github.com/buscaresgatados/pesquisa-listas/actions

